const menuNav = {
    home: 'HOME',
    menu: 'MENU',
    catering: 'CATERING',
    aboutus: 'ABOUT US',
};

const homePage = {
    firstTitle: 'ABC RESTAURANT',
    firstDescreption: 'STRØMMEN',
    aboutus: 'ABOUT US',
    aboutusDescription: 'ABC RESTAURANT IS A FAMILY BUSINESS WITH OVER SO YEARS OF EXPERIENCE IN THE INDUSTRY\n'
        + 'WE WANT TO OFFER YOU AN EXPERIENCE IN ASIAN FLAVORS\n'
        + 'WITH US WE HAVE A LA CARTE, SUNDAY BUFFER, CATERING SOLUTIONS AND TAKE AWAY\n'
        + 'IN ADDITION WE ALSO HAVE BANQUEETING ROOMS THAT YOU CAN BOOK FOR COURES\n'
        + 'AND CONFERENCES OR FOR OTHER SPECIAL EVENTS\n'
        + 'THE RESTAURANT IS CENTRALLY LOCATED ON STRØMMEN CLOSE TO STRØMMEN STORSENTER',
}
module.exports = {
    menuNav,
    homePage,
}